Platform Validator
pinakipb2/CP-Parse-Kit pull request #1
Opened 2023-09-09 06:42 UTC by sarkar1619

Done with ConfigParser and PlatformValidator.

2023-09-10 18:24 UTC, pinakipb2 requested changes

2023-09-10 18:24 UTC, pinakipb2 commented on architecture/TODO.md
>  - [ ] config.json (root dir) should be of type as given in architecture
Mark as complete for the items that has been completed.

2023-09-18 16:19 UTC, sarkar1619 commented on architecture/TODO.md
>  - [ ] config.json (root dir) should be of type as given in architecture
Done

2023-09-18 16:20 UTC, pinakipb2 approved these changes

2023-09-18 16:35 UTC, merged